version: "3.7"

services:
  app:
    container_name: backend-product-ac5
    build: 
      context: .
      dockerfile: ./dockerfile
    env_file: .env-docker
    ports: 
      - 8000
    depends_on:
      - database
    links:
      - database:database
    networks:
      - default
      - backend

  nginx:
    container_name: nginx-proxy-ac5
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - default
      - backend

  database:
    image: postgres:12-alpine
    container_name: database-postgres-ac5
    env_file: .env-docker
    ports:
      - 5433:5432
    networks:
      - default
      - backend

networks: 
  backend:
